import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from "node:fs";
import path from "node:path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// === 自動コピー先の設定 ===
const vaultPath = "/home/kz003/atelier/obsidian-vault/";
const pluginDir = path.join(vaultPath, ".obsidian/plugins/obsidian-asset-weaver");

const copyToVault = {
	name: 'copy-to-vault',
	setup(build) {
		build.onEnd(() => {
			if (!fs.existsSync(pluginDir)) {
				fs.mkdirSync(pluginDir, { recursive: true });
			}
			// 必要なファイルをコピー
			fs.copyFileSync("main.js", path.join(pluginDir, "main.js"));
			if (fs.existsSync("manifest.json")) fs.copyFileSync("manifest.json", path.join(pluginDir, "manifest.json"));
			if (fs.existsSync("styles.css")) fs.copyFileSync("styles.css", path.join(pluginDir, "styles.css"));
			
			console.log(`Build complete. Files copied to ${pluginDir}`);
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: fs.existsSync(vaultPath) ? [copyToVault] : [], // Vaultが存在する場合のみコピーを実行
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
