import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from "node:fs";
import path from "node:path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Load local settings if they exist
let vaultPath = "";
if (fs.existsSync("local-settings.json")) {
	try {
		const settings = JSON.parse(fs.readFileSync("local-settings.json", "utf8"));
		vaultPath = settings.vaultPath;
	} catch (e) {
		console.error("Error reading local-settings.json:", e);
	}
}

const pluginDir = vaultPath ? path.join(vaultPath, ".obsidian/plugins/asset-weaver") : "";

const copyToVault = {
	name: 'copy-to-vault',
	setup(build) {
		build.onEnd(() => {
			if (!pluginDir) return;

			if (!fs.existsSync(pluginDir)) {
				fs.mkdirSync(pluginDir, { recursive: true });
			}
			// Copy necessary files
			fs.copyFileSync("main.js", path.join(pluginDir, "main.js"));
			if (fs.existsSync("manifest.json")) fs.copyFileSync("manifest.json", path.join(pluginDir, "manifest.json"));
			if (fs.existsSync("styles.css")) fs.copyFileSync("styles.css", path.join(pluginDir, "styles.css"));
			
			console.log(`Build complete. Files copied to ${pluginDir}`);
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: pluginDir ? [copyToVault] : [], 
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
